apiVersion: apps/v1
kind: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filrouge
  labels:
    app: filrouge
spec:
  selector:
    matchLabels:
      app: filrouge
  replicas: 5
  template:
    metadata:
      labels:
        app: filrouge
    spec:
      volumes:
        - name: app-auth
          hostPath:
            path: /filrouge/.sec
            type: Directory
      containers:
      - name: filrouge
        image: hlamy/sio2021:latest
        volumeMounts:
          - name: app-auth
            mountPath: /.sec
        ports:
        - containerPort: 5555
      imagePullSecrets:
      - name: regcred