version: '3'

services:
    filrouge:
        build: .
        volumes :
          - $HOME/.aws:/app/.aws:ro
        ports:
          - "5555-5559:25252"
 
    nginx:
        build: ./nginx
        ports:
          - "5550:80"
        depends_on:
          - filrouge
