version: '3'

services:
    filrouge:
        build: .
        volumes :
          - $HOME/.aws:/app/.aws:ro
          - ./.sec:/.sec
        ports:
          - "5555-5559:5555"
 
    nginx:
        build: ./nginx
        volumes :
          - ./.sec:/etc/nginx/ssl/filrouge.lmy.p2021.ajoga.fr/
        ports:
          - "5550:443"
        depends_on:
          - filrouge
