version: '3'

services:
    filrouge:
        build: .
        volumes :
          - $HOME/.aws:/app/.aws:ro
          - $HOME/.auth/auth:/
        ports:
          - "5555-5559:5555"
 
    nginx:
        build: ./nginx
        ports:
          - "5550:443"
        depends_on:
          - filrouge
