apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  type: NodePort
  selector:
    app: filrouge
  ports:
    - port: 5555
      targetPort: 5555
      nodePort: 30009
      protocol: TCP