FROM nginx

COPY server.crt /etc/nginx/ssl/filrouge.lmy.p2021.ajoga.fr/
COPY server.key /etc/nginx/ssl/filrouge.lmy.p2021.ajoga.fr/

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf