apiVersion: apps/v1
kind: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filrouge
  labels:
    app: filrouge
spec:
  selector:
    matchLabels:
      app: filrouge
  replicas: 5
  template:
    metadata:
      labels:
        app: filrouge
    spec:
      volumes:
        - name: aws
          hostPath:
            path: $HOME/.aws
            type: Directory
      containers:
      - name: filrouge
        image: filrouge:latest
        volumeMounts:
          - name: aws
            mountPath: /app/.aws
        ports:
        - containerPort: 5555
        